module.exports = {
  // "app.js":  require('./app.js'),
  // "theme.js": require('./theme.js'),
  "blob-url.js":  require('./blob-url.js'),
  "crypto.js":  require('./crypto.js'),
  // "file-input.js":  require('./file-input.js'),
  // "menu.js":  require('./menu.js'),
  // "message-confirm.js":  require('./message-confirm.js'),
  "sbot.js": require('./sbot.js'),
  // "about.js":  require('./about.js'),
  // "avatar-edit.js":  require('./avatar-edit.js'),
  "avatar-image.js":  require('./avatar-image.js'),
  // "avatar-link.js":  require('./avatar-link.js'),
  // "avatar-name.js":  require('./avatar-name.js'),
  // "avatar-profile.js":  require('./avatar-profile.js'),
  // "avatar.js":  require('./avatar.js'),
  // "compose.js":  require('./compose.js'),
  // "feed.js":  require('./feed.js'),
  // "follow.js":  require('./follow.js'),
  // "invite.js":  require('./invite.js'),
  // "star.js":  require('./star.js'),
  "markdown.js":  require('./markdown.js'),
  // "message-link.js":  require('./message-link.js'),
  "message-name.js":  require('./message-name.js'),
  // "message.js":  require('./message.js'),
  // "identify.js": require('./identify.js'),
  "names.js":  require('./names.js'),
  // "raw.js":  require('./raw.js'),
  // "post.js":  require('./post.js'),
  // "private.js":  require('./private.js'),
  // "public.js":  require('./public.js'),
  // "network.js":  require('./network.js'),
  // "relationships.js":  require('./relationships.js'),
  // "suggest-mentions.js":  require('./suggest-mentions.js'),
  "thread.js":  require('./thread.js'),
  // "timestamp.js":  require('./timestamp.js'),
  "emoji.js":  require('./emoji.js'),
  // "suggest-emoji.js":  require('./suggest-emoji.js'),
  // "git.js":  require('./git.js'),
  // "key.js":  require('./key.js'),
  // "notifications.js":  require('./notifications.js'),
  // "search.js": require('./search')
}
